function Analytics() {
  const performance = [
    {
      title: "Block Optimization",
      value: 92,
      description: "Optimal maintenance windows selected",
    },
    {
      title: "Train Disruption Reduction",
      value: 84,
      description: "Reduction in expected train conflicts",
    },
    {
      title: "Asset Utilization",
      value: 96,
      description: "Railway assets available for operations",
    },
  ];

  const monthlyData = [
    {
      metric: "Asset Availability",
      previous: "93%",
      current: "96%",
      improvement: "+3%",
    },
    {
      metric: "Average Delay",
      previous: "8.5 min",
      current: "7 min",
      improvement: "-18%",
    },
    {
      metric: "Block Optimization",
      previous: "86%",
      current: "92%",
      improvement: "+6%",
    },
    {
      metric: "AI Confidence",
      previous: "89%",
      current: "94%",
      improvement: "+5%",
    },
  ];

  return (
    <div className="page-container">

      {/* PAGE HEADER */}
      <div className="page-header">
        <div>
          <h1>📊 Analytics & Performance</h1>
          <p>
            Analyze AI-powered block planning and railway operational
            performance.
          </p>
        </div>

        <span className="header-badge">AI PERFORMANCE</span>
      </div>

      {/* SUMMARY CARDS */}
      <section className="stats-grid">

        <div className="stat-card">
          <div className="stat-icon">🛤️</div>
          <div>
            <p>Asset Availability</p>
            <h2>96%</h2>
            <span className="positive">↑ 3% improvement</span>
          </div>
        </div>

        <div className="stat-card">
          <div className="stat-icon">🚆</div>
          <div>
            <p>Trains Optimized</p>
            <h2>128</h2>
            <span className="positive">AI optimized</span>
          </div>
        </div>

        <div className="stat-card">
          <div className="stat-icon">⏱️</div>
          <div>
            <p>Delay Reduction</p>
            <h2>18%</h2>
            <span className="positive">Operational improvement</span>
          </div>
        </div>

        <div className="stat-card">
          <div className="stat-icon">🤖</div>
          <div>
            <p>AI Accuracy</p>
            <h2>94%</h2>
            <span className="positive">High confidence</span>
          </div>
        </div>

      </section>

      {/* OPTIMIZATION PERFORMANCE */}
      <section className="recommendation-card">
        <div className="section-title">
          <div>
            <h2>⚡ Optimization Performance</h2>
            <p>
              Performance indicators generated by the AI block planner.
            </p>
          </div>

          <span className="recommended-badge">AI ANALYTICS</span>
        </div>

        <div style={{ marginTop: "25px" }}>

          {performance.map((item) => (
            <div key={item.title} style={{ marginBottom: "25px" }}>

              <div
                style={{
                  display: "flex",
                  justifyContent: "space-between",
                  marginBottom: "8px",
                }}
              >
                <div>
                  <strong>{item.title}</strong>
                  <p
                    style={{
                      margin: "4px 0 0",
                      color: "#6b7280",
                      fontSize: "14px",
                    }}
                  >
                    {item.description}
                  </p>
                </div>

                <strong>{item.value}%</strong>
              </div>

              <div
                style={{
                  width: "100%",
                  height: "10px",
                  background: "#e5e7eb",
                  borderRadius: "10px",
                  overflow: "hidden",
                }}
              >
                <div
                  style={{
                    width: `${item.value}%`,
                    height: "100%",
                    background: "#172033",
                    borderRadius: "10px",
                  }}
                ></div>
              </div>

            </div>
          ))}

        </div>
      </section>

      {/* AI PLANNING SUMMARY */}
      <section className="dashboard-grid" style={{ marginTop: "25px" }}>

        <div className="recommendation-card">
          <div className="section-title">
            <div>
              <h2>🤖 AI Planning Summary</h2>
              <p>Overview of the AI decision-making process.</p>
            </div>

            <span className="recommended-badge">AI ENGINE</span>
          </div>

          <div className="recommendation-details">

            <div>
              <span>Blocks Evaluated</span>
              <strong>186</strong>
            </div>

            <div>
              <span>Optimal Blocks Selected</span>
              <strong>128</strong>
            </div>

            <div>
              <span>Average Delay</span>
              <strong>7 min</strong>
            </div>

            <div>
              <span>Asset Availability</span>
              <strong>96%</strong>
            </div>

          </div>
        </div>

        {/* AI EXPLANATION */}
        <div className="impact-card">

          <h2>🧠 How AI Helps</h2>

          <p>
            The AI-powered planner evaluates railway maintenance
            requirements, train schedules, asset conditions and
            operational constraints.
          </p>

          <div className="impact-item">
            <span>1. Analyze Assets</span>
            <strong>✓</strong>
          </div>

          <div className="impact-item">
            <span>2. Evaluate Train Conflicts</span>
            <strong>✓</strong>
          </div>

          <div className="impact-item">
            <span>3. Select Best Block</span>
            <strong>✓</strong>
          </div>

          <div className="impact-item">
            <span>4. Minimize Delays</span>
            <strong>✓</strong>
          </div>

        </div>

      </section>

      {/* MONTHLY PERFORMANCE */}
      <section className="table-card" style={{ marginTop: "25px" }}>

        <div className="table-header">
          <div>
            <h2>📈 Monthly Performance</h2>
            <p>
              Comparison of railway operational performance.
            </p>
          </div>
        </div>

        <table>

          <thead>
            <tr>
              <th>Performance Metric</th>
              <th>Previous</th>
              <th>Current</th>
              <th>Improvement</th>
            </tr>
          </thead>

          <tbody>

            {monthlyData.map((item) => (
              <tr key={item.metric}>

                <td>
                  <strong>{item.metric}</strong>
                </td>

                <td>{item.previous}</td>

                <td>
                  <strong>{item.current}</strong>
                </td>

                <td>
                  <span className="status completed">
                    {item.improvement}
                  </span>
                </td>

              </tr>
            ))}

          </tbody>

        </table>

      </section>

      {/* DATA NOTE */}
      <div
        style={{
          marginTop: "20px",
          padding: "15px 20px",
          background: "#f8fafc",
          borderRadius: "10px",
          border: "1px solid #e5e7eb",
          color: "#6b7280",
          fontSize: "13px",
        }}
      >
        <strong>Project Demo Data:</strong> The analytics values shown on
        this page are sample project data used to demonstrate the
        AI-powered railway block planning system.
      </div>

    </div>
  );
}

export default Analytics;